name: Build and Test

on: [push]

concurrency:
  group: build_and_test_group_${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      # Checkout Step
      - uses: actions/checkout@v1

      # Dependencies
      - name: Install Dependencies
        env:
